# Generated by Django 4.2.1 on 2023-08-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="criado em"),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="pago")),
            ],
            options={
                "verbose_name": "inscricao",
                "verbose_name_plural": "inscrições",
                "ordering": ("-created_at",),
            },
        ),
    ]
