# Generated by Django 4.2.1 on 2023-10-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("title", models.CharField(max_length=100, verbose_name="título")),
                ("slug", models.SlugField(verbose_name="slug")),
                ("photo", models.URLField(verbose_name="foto")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="criado em"),
                ),
            ],
            options={
                "verbose_name": "palestrante",
                "verbose_name_plural": "palestrantes",
            },
        ),
    ]
