# Generated by Django 4.2.1 on 2023-11-21 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_course_abc_to_mti"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseOld",
        ),
    ]
